version: '2'
services:
  couchdb:
    image: "apache/couchdb:1.7.1"
    environment:
      - COUCHDB_USER=user
      - COUCHDB_PASSWORD=password
    ports:
      - "5984:5984"
  configdb:
    build: "."
    environment:
      - COUCHDB_USER=user
      - COUCHDB_PASSWORD=password
      - COUCHDB_HOST=couchdb
      - COUCHDB_PORT=5984      
      - PORT=8080  
    ports:
      - "8080:8080"